[package]
name = "jq-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.89"
assert_cmd = "2.0.16"
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
predicates = "3.1.2"
serde = "1.0.210"
serde_json = "1.0.128"
